# Generated by Django 5.2.3 on 2025-06-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_HP', models.IntegerField()),
                ('max_HP', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('player', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CombatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('combat_index', models.IntegerField()),
                ('characters', models.ManyToManyField(to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
                ('combat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.combatsession')),
            ],
            options={
                'ordering': ['-initiative'],
                'unique_together': {('character', 'combat_session')},
            },
        ),
    ]
