# Generated by Django 5.2.3 on 2025-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatsession',
            name='characters',
            field=models.ManyToManyField(to='api.combatparticipant'),
        ),
    ]
