# Generated by Django 5.2.3 on 2025-07-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_combatsession_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatsession',
            name='characters',
        ),
    ]
