# Generated by Django 5.2.3 on 2025-07-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_combatsession_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatsession',
            name='characters',
            field=models.ManyToManyField(to='api.character'),
        ),
    ]
