# Generated by Django 5.2.3 on 2025-07-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_combatsession_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatsession',
            name='participants',
            field=models.ManyToManyField(through='api.CombatParticipant', to='api.character'),
        ),
    ]
