# Generated by Django 5.2.3 on 2025-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_combatsession_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatsession',
            name='participants',
            field=models.ManyToManyField(help_text='Select participants', through='api.CombatParticipant', to='api.character'),
        ),
    ]
