# Generated by Django 5.2.3 on 2025-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_combatsession_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatsession',
            name='characters',
            field=models.ManyToManyField(to='api.combatparticipant'),
        ),
    ]
