# Generated by Django 5.2.3 on 2025-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_combatsession_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatsession',
            name='characters',
            field=models.ManyToManyField(to='api.character'),
        ),
    ]
