# Generated by Django 5.2.3 on 2025-07-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_combatsession_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatsession',
            name='characters',
            field=models.ManyToManyField(blank=True, to='api.combatparticipant'),
        ),
    ]
