# Generated by Django 5.2.3 on 2025-07-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_combatsession_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatsession',
            name='characters',
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-init']},
        ),
        migrations.AddField(
            model_name='character',
            name='combat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.combatsession'),
        ),
        migrations.AddField(
            model_name='character',
            name='init',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CombatParticipant',
        ),
    ]
