# Generated by Django 5.2.3 on 2025-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_combatsession_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatsession',
            name='combat_index',
            field=models.IntegerField(default=0),
        ),
    ]
