# Generated by Django 5.2.3 on 2025-07-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_character_owner_combatsession_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='combat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.combatsession'),
        ),
    ]
