# Generated by Django 5.2.3 on 2025-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_character_combat_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.CharField(default='Wizard', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
